### ISSUE TITLE
 Allocator (GPU_0_bfc) ran out of memory

### ISSUE THREAD

**Issue by collado1992** [aws-deepracer-community/deepracer-for-cloud#12]
![Screenshot from 2019-08-09 18-09-29](https://user-images.githubusercontent.com/20427437/62809490-7972ab00-bad1-11e9-8411-045b51bcd0fa.png)
The simulation started good, but in the third checkpoint the console output a tensorflow  bad allocator (see the picture) .
What is happening?
Thanks

**Comment by sideshow-dan** [comment]
Same issue here.

**Comment by pablobacho** [comment]
How much memory does your GPU have? Mine has 4GB and it happens kind of randomly to me. For what I read lowering the batch size is supposed to help at the expense of longer training.
What I do is:
`./stop.sh`
`sudo ./set-last-run-to-pretrained.sh`
`sudo ./delete-last-run.sh`
Change rl_deepracer_coach_robomaker.py to pretrained (commented-out hyperparameters)
`./start.sh`
And it looks like it keeps training where it was, except for the last iteration I guess.

**Comment by collado1992** [comment]
Hi @pablobacho. I do the same. I have 4 GB in my GPU. it is random, some times and in some tracks occurs a few minutes after the start and for others after 2 or more hours.  Thanks

**Comment by sideshow-dan** [comment]
I tried several things without success. I start doing as proposed above. Only thing is after it failed I have to switch to CPU only, it always fails on similar situations. One thing that I did that may helped is, I cleaned the GPU (display are on Intel onboarding chipset) and all memory are use for ML training.

Thanks for the help

**Comment by acidfreako** [comment]
i got to episode 80 with gtx 1650 super 4gb ram. batch size 32 and episode 20

reducing episode to 10 doesnt seems to improve any further.

Tried pablo suggestion but does not give any better luck

**Comment by acidfreako** [comment]
[related issue 49 ](https://github.com/crr0004/deepracer/issues/49)

**Comment by acidfreako** [comment]
actually i will try again tonight i missed out this step 
"Change rl_deepracer_coach_robomaker.py to pretrained (commented-out hyperparameters)"

**Comment by Lukanite** [comment]
I tried doing this, but simply from uncommenting those two lines, ./start.sh no longer shows the training window, and the car doesn't move. If I re-comment those lines, it works again (but no pre-trained model is used).

**Comment by Lukanite** [comment]
I'm an idiot - remember to add a comma to the end of the line for "term_cond_avg_score" right above the lines being uncommented, folks

**Comment by Lukanite** [comment]
So, I gave this a shot and it looks like it fails with the same OOM error - it just loads the checkpoint, does 20 episodes, starts trying to train, and then dies. So it looks like I'm stuck forever at generation 3. I've also decreased my batch_size to 32 but that doesn't seem to help (This is running on a RTX 2070, btw)

**Comment by acidfreako** [comment]
yea it looks like I am having the same issue

**Comment by acidfreako** [comment]
https://gist.github.com/amgorb/c38a77599c1f30e853cc9babf596d634
https://redis.io/topics/clients
https://github.com/jarrettj/deepracer-ami/blob/master/README.md

**Comment by acidfreako** [comment]
this worked for me from the above articles

> sudo sysctl vm.overcommit_memory=1    # this allows docker to take more memory than what is required
sudo sysctl -w net.core.somaxconn=512  # did this because rl_coach is set to enforce 511 for TCP backlog.
sudo su
echo never > /sys/kernel/mm/transparent_hugepage/enabled   #this one should be ran anytime you reboot the system haven't bother to automate it

and 

> Increase buffer limit to 10GB
docker exec -t $(docker ps | grep sagemaker | cut -d' ' -f1) redis-cli config set client-output-buffer-limit 'slave 10737418240 10737418240 0'

Set max memory to 10GB
docker exec -t $(docker ps | grep sagemaker | cut -d' ' -f1) redis-cli config set maxmemory 10737418240

**Comment by acidfreako** [comment]
in hyperparameter , for epoch value use 10 for stable slower training.

i also set my episode to 5 to write more regular check points

**Comment by acidfreako** [comment]
still getting OOM after a few run

**Comment by Lukanite** [comment]
I don't think it's a system memory problem, but rather a GPU memory issue, judging by the error message

**Comment by acidfreako** [comment]
![batch2episod2 -1 ](https://user-images.githubusercontent.com/29254801/71825094-36a01800-30ef-11ea-81bb-b30eb74fd5b3.png)

this works for 6.5 hrs without crashing on 1650 super 4gb gpu ram. will try to push the limit more tomorrow.

**Comment by acidfreako** [comment]
![Screenshot from 2020-01-07 21-36-07](https://user-images.githubusercontent.com/29254801/71889216-c7313380-3195-11ea-89ff-50b4f5e039d3.png)


1650 super 4gb seems to be able to handle this parameters without crashing.

**Comment by acidfreako** [comment]
![Screenshot from 2020-01-07 23-07-48](https://user-images.githubusercontent.com/29254801/71894520-9c011100-31a2-11ea-809a-452554df1f3b.png)
the max setting i can use for 1650 super 4gb

**Comment by mfouadthabet** [comment]
I confirm these problems.
Could not have a decent training session , the best so far is 67K steps  and then the OOM crash 
and then it keeps on crashing without reaching a better checkpoint.

In addition after a crash , I see that the GPU memory is still full until I issue a ./stop.sh 
and I have to delete all .finished files and folders (2 files and one folder) before issuing a new ./start.sh

"batch_size": 16,
 "num_epochs": 10,
"num_episodes_between_training" : 10,

GPU is 1080 xi  12 GB memory

**I have two questions:**
 - I have another GPU on the same machine , but do not know how to get it to be used in the training.
 - Will the stack size parameter help in any way?! (at default value of 1)

**Any help is appreciated.
Thanks.**

**Comment by acidfreako** [comment]
@mfouadthabet  reduce batch_size to 4 and episode to 3 ? and see how you go ?  slowly increment from there.

I manage to get stable run with batch size 4 and 3 episode for 1650 super 4gb RAM

**Comment by acidfreako** [comment]
if you have more than 1 GPU you need to update the nvidia image somewhere to utilise all GPUs.

**Comment by mfouadthabet** [comment]
Using batch_size 4 and "num_episodes_between_training" : 5  ,  "num_epochs": 10 did not produce OOM error. But it resulted in NaN

`Policy training> Surrogate loss=0.000304431829135865, KL divergence=nan, Entropy=nan, training epoch=8, learning_rate=0.00035
Policy training> Surrogate loss=-9.91132837953046e-05, KL divergence=nan, Entropy=nan, training epoch=9, learning_rate=0.00035
/usr/local/lib/python3.6/dist-packages/numpy/core/_methods.py:26: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims)
/usr/local/lib/python3.6/dist-packages/numpy/core/_methods.py:29: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims)
{"simapp_exception": {"version": "1.0", "date": "2020-01-09 04:33:25.333527", "function": "training_worker", "message": "NaN detected in loss function, aborting training. Job failed!", "exceptionType": "training_worker.exceptions", "eventType": "system_error", "errorCode": "503"}}`

This is maybe because batch size 4 is too low , I will try with different reward function.
Does the samples reward functions converge ? it is expected to be slow , but will it converge?
something like this:

[https://docs.aws.amazon.com/deepracer/latest/developerguide/deepracer-reward-function-examples.html#deepracer-reward-function-example-0](url)

**Comment by acidfreako** [comment]
remove .finished file

https://codelikeamother.uk/training-locally-for-aws-deepracer-and-a-udacity-challenge-with-rewards

**Comment by minshi-cognite** [comment]
> @mfouadthabet reduce batch_size to 4 and episode to 3 ? and see how you go ? slowly increment from there.
> 
> I manage to get stable run with batch size 4 and 3 episode for 1650 super 4gb RAM
> 
> check my post.

I reduced batch_size to 4 and episode to 3 as you suggested. I have 4GB GPU. After 120 checkpoints, the training process is still crashed. The racer is able to drive following the track. However, comparing to the training result I achieved using aws cloud. the racer drive much slower than what I can achieved using cloud training. Do you have experience to train it using CPU? I have set gpu_available to false, but still the training process continue using GPU and get crash.

**Comment by pmac-code** [comment]
Is there any update on how to resolve this issue as I'm currently experiencing it, and i have tried reducing the batch size sadly no luck

**Comment by larsll** [comment]
@pmac-code - try to reduce the number of episodes per iteration. Default is 20; try 10.
